-- MySQL Script generated by MySQL Workbench
-- Thu Oct 17 12:25:39 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema SkgDatabase
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `SkgDatabase` ;

-- -----------------------------------------------------
-- Schema SkgDatabase
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SkgDatabase` DEFAULT CHARACTER SET utf8 ;
USE `SkgDatabase` ;

-- -----------------------------------------------------
-- Table `SkgDatabase`.`PropertyTypeMapping`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SkgDatabase`.`PropertyTypeMapping` ;

CREATE TABLE IF NOT EXISTS `SkgDatabase`.`PropertyTypeMapping` (
  `property_type` TINYINT(1) NOT NULL,
  `type_title` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`property_type`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SkgDatabase`.`SaleTypeMapping`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SkgDatabase`.`SaleTypeMapping` ;

CREATE TABLE IF NOT EXISTS `SkgDatabase`.`SaleTypeMapping` (
  `sale_type` TINYINT(1) NOT NULL,
  `type_title` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`sale_type`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SkgDatabase`.`Properties`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SkgDatabase`.`Properties` ;

CREATE TABLE IF NOT EXISTS `SkgDatabase`.`Properties` (
  `id` INT NOT NULL,
  `price` INT NOT NULL,
  `sqm` INT NOT NULL,
  `location` VARCHAR(45) NOT NULL,
  `bedrooms` INT NOT NULL,
  `bathrooms` INT NOT NULL,
  `property_type` TINYINT(1) NOT NULL,
  `floor` INT NOT NULL,
  `description` VARCHAR(400) NULL,
  `sale_type` TINYINT(1) NOT NULL,
  `phone` VARCHAR(10) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `img_url` VARCHAR(100) NULL,
  `furnitured` TINYINT(1) NOT NULL,
  `heating_type` VARCHAR(45) NOT NULL,
  `built_year` INT NOT NULL,
  `parking` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) ,
  INDEX `property_type_idx` (`property_type` ASC) ,
  INDEX `sale_type_idx` (`sale_type` ASC) ,
  CONSTRAINT `property_type`
    FOREIGN KEY (`property_type`)
    REFERENCES `SkgDatabase`.`PropertyTypeMapping` (`property_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `sale_type`
    FOREIGN KEY (`sale_type`)
    REFERENCES `SkgDatabase`.`SaleTypeMapping` (`sale_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
